import { Document, Page, Text, View, type DocumentProps } from "@react-pdf/renderer";
import type { ReactElement } from "react";
import type { LeaseSummaryPdfData } from "./pdf-data";
import { styles } from "./pdf-styles";

interface LeaseSummaryPdfDocumentProps {
  data: LeaseSummaryPdfData;
}

function DetailRow({ label, value, last = false }: { label: string; value: string; last?: boolean }) {
  const rowStyles = last ? [styles.row, styles.rowLast] : [styles.row];

  return (
    <View style={rowStyles}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

export function LeaseSummaryPdfDocument({ data }: LeaseSummaryPdfDocumentProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.brandRow}>
            <View style={styles.brandMark}>
              <Text style={styles.brandMarkText}>D</Text>
            </View>
            <View>
              <Text style={styles.brandName}>Domus</Text>
              <Text style={styles.brandSubtitle}>LEASE SUMMARY</Text>
            </View>
          </View>
          <View style={styles.headerMeta}>
            <Text style={styles.headerMetaLabel}>Generated</Text>
            <Text style={styles.headerMetaValue}>{data.generatedAt}</Text>
          </View>
        </View>

        <Text style={styles.title}>Lease Summary</Text>
        <Text style={styles.subtitle}>Reference summary for {data.propertyName}</Text>

        <View style={styles.accentPanel}>
          <Text style={styles.emphasisText}>{data.leaseNumber}</Text>
          <Text style={styles.helperText}>{data.leaseStatusLabel} lease for {data.unitLabel}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Resident and Property</Text>
          <View style={styles.panel}>
            <DetailRow label="Tenant" value={data.tenantName} />
            <DetailRow label="Tenant Email" value={data.tenantEmail} />
            <DetailRow label="Property" value={data.propertyName} />
            <DetailRow label="Address" value={data.propertyAddress} />
            <DetailRow label="Unit" value={data.unitLabel} last />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Lease Terms</Text>
          <View style={styles.panel}>
            <DetailRow label="Lease Period" value={data.leasePeriodLabel} />
            <DetailRow label="Monthly Rent" value={data.monthlyRentFormatted} />
            <DetailRow label="Security Deposit" value={data.depositFormatted} />
            <DetailRow label="Due Day" value={data.dueDayLabel} />
            <DetailRow label="Grace Period" value={data.gracePeriodLabel} />
            <DetailRow label="Late Fee" value={data.lateFeeFormatted} last />
          </View>
        </View>

        <Text style={styles.footer}>Generated by Domus - domusbase.com - {data.generatedAt}</Text>
      </Page>
    </Document>
  );
}

export function createLeaseSummaryPdfDocument(
  props: LeaseSummaryPdfDocumentProps
): ReactElement<DocumentProps> {
  return <LeaseSummaryPdfDocument {...props} />;
}
