import { Document, Page, Text, View, type DocumentProps } from "@react-pdf/renderer";
import type { ReactElement } from "react";
import type { ManagerInvoicePdfData } from "@/lib/manager-payments";
import { colors, styles } from "./pdf-styles";

interface ManagerInvoiceDocumentProps {
  invoice: ManagerInvoicePdfData;
}

function DetailRow({ label, value, last = false }: { label: string; value: string; last?: boolean }) {
  return (
    <View style={last ? [styles.row, styles.rowLast] : styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

function StatusBadge({ status }: { status: string }) {
  const backgroundColor = status.toLowerCase() === "paid" ? colors.success : colors.primary;

  return (
    <Text style={[styles.badge, { backgroundColor }]}>{status.toUpperCase()}</Text>
  );
}

export function ManagerInvoicePdfDocument({ invoice }: ManagerInvoiceDocumentProps) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <View style={styles.brandRow}>
            <View style={styles.brandMark}>
              <Text style={styles.brandMarkText}>D</Text>
            </View>
            <View>
              <Text style={styles.brandName}>Domus</Text>
              <Text style={styles.brandSubtitle}>MANAGER PAYMENT INVOICE</Text>
            </View>
          </View>
          <View style={styles.headerMeta}>
            <Text style={styles.headerMetaLabel}>Invoice date</Text>
            <Text style={styles.headerMetaValue}>{invoice.invoiceDate}</Text>
          </View>
        </View>

        <Text style={styles.title}>Invoice</Text>
        <Text style={styles.subtitle}>{invoice.category} for {invoice.propertyName}</Text>
        <StatusBadge status={invoice.status} />

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <View style={styles.panel}>
            <DetailRow label="Invoice Number" value={invoice.invoiceNumber} />
            <DetailRow label="Property" value={invoice.propertyName} />
            <DetailRow label="Address" value={invoice.propertyAddress} />
            <DetailRow label="From" value={`${invoice.fromName} (${invoice.fromEmail})`} />
            <DetailRow label="To" value={`${invoice.toName} (${invoice.toEmail})`} last />
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Line Items</Text>
          <View style={styles.panel}>
            {invoice.lineItems.map((item, index) => (
              <DetailRow
                key={`${item.description}-${index}`}
                label={item.description}
                value={item.amount}
                last={index === invoice.lineItems.length - 1}
              />
            ))}
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total</Text>
              <Text style={styles.totalValue}>{invoice.totalFormatted}</Text>
            </View>
          </View>
        </View>

        {invoice.notes ? (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Notes</Text>
            <View style={styles.accentPanel}>
              <Text style={styles.helperText}>{invoice.notes}</Text>
            </View>
          </View>
        ) : null}

        <Text style={styles.footer}>Generated by Domus - domusbase.com - {invoice.generatedAt}</Text>
      </Page>
    </Document>
  );
}

export function createManagerInvoicePdfDocument(
  props: ManagerInvoiceDocumentProps
): ReactElement<DocumentProps> {
  return <ManagerInvoicePdfDocument {...props} />;
}
