import { Document, Page, Text, View, type DocumentProps } from "@react-pdf/renderer";
import type { ReactElement } from "react";
import { formatDateTime } from "@/lib/format";
import type { ReceiptPdfData } from "./pdf-data";
import { styles } from "./pdf-styles";

interface ReceiptPdfDocumentProps {
  receipts: ReceiptPdfData[];
  exportLabel?: string;
}

function BrandHeader({ generatedAt, exportLabel }: { generatedAt: string; exportLabel?: string }) {
  return (
    <View style={styles.header}>
      <View style={styles.brandRow}>
        <View style={styles.brandMark}>
          <Text style={styles.brandMarkText}>D</Text>
        </View>
        <View>
          <Text style={styles.brandName}>Domus</Text>
          <Text style={styles.brandSubtitle}>RENTAL COMMAND CENTER</Text>
        </View>
      </View>
      <View style={styles.headerMeta}>
        <Text style={styles.headerMetaLabel}>{exportLabel ?? "Generated"}</Text>
        <Text style={styles.headerMetaValue}>{generatedAt}</Text>
      </View>
    </View>
  );
}

function DetailRow({ label, value, last = false }: { label: string; value: string; last?: boolean }) {
  const rowStyles = last ? [styles.row, styles.rowLast] : [styles.row];

  return (
    <View style={rowStyles}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{value}</Text>
    </View>
  );
}

function ReceiptPage({ receipt }: { receipt: ReceiptPdfData }) {
  return (
    <Page size="LETTER" style={styles.page}>
      <BrandHeader generatedAt={receipt.generatedAt} exportLabel="Receipt created" />
      <Text style={styles.title}>Payment Receipt</Text>
      <Text style={styles.subtitle}>{receipt.categoryLabel} payment confirmation for {receipt.propertyName}</Text>
      <Text style={styles.badge}>PAID</Text>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Payment Details</Text>
        <View style={styles.panel}>
          <DetailRow label="Receipt Number" value={receipt.receiptNumber} />
          <DetailRow label="Tenant" value={receipt.tenantName} />
          <DetailRow label="Property" value={receipt.propertyName} />
          <DetailRow label="Address" value={receipt.propertyAddress} />
          <DetailRow label="Unit" value={receipt.unitLabel} />
          <DetailRow label="Lease Period" value={receipt.leaseLabel} />
          <DetailRow label="Due Date" value={receipt.dueDate} />
          <DetailRow label="Payment Date" value={receipt.paidDate} />
          <DetailRow label="Method" value={receipt.paymentMethod} />
          {receipt.referenceNote ? <DetailRow label="Reference" value={receipt.referenceNote} /> : null}
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Amount Paid</Text>
            <Text style={styles.totalValue}>{receipt.amountFormatted}</Text>
          </View>
        </View>
      </View>

      <Text style={styles.footer}>Generated by Domus - domusbase.com - {receipt.generatedAt}</Text>
    </Page>
  );
}

function EmptyReceiptExportPage({ exportLabel }: { exportLabel?: string }) {
  const generatedAt = formatDateTime(new Date());

  return (
    <Page size="LETTER" style={styles.page}>
      <BrandHeader generatedAt={generatedAt} exportLabel={exportLabel} />
      <Text style={styles.emptyStateTitle}>No receipts found</Text>
      <Text style={styles.emptyStateBody}>
        There were no paid receipts for the selected filters. Adjust the year and try the export again.
      </Text>
      <Text style={styles.footer}>Generated by Domus - domusbase.com - {generatedAt}</Text>
    </Page>
  );
}

export function ReceiptPdfDocument({ receipts, exportLabel }: ReceiptPdfDocumentProps) {
  return (
    <Document>
      {receipts.length > 0
        ? receipts.map((receipt) => <ReceiptPage key={receipt.receiptNumber} receipt={receipt} />)
        : <EmptyReceiptExportPage exportLabel={exportLabel} />}
    </Document>
  );
}

export function createReceiptPdfDocument(
  props: ReceiptPdfDocumentProps
): ReactElement<DocumentProps> {
  return <ReceiptPdfDocument {...props} />;
}
