import type { DashboardData } from "@/lib/dashboard";
import type { NotificationPreferenceSettings } from "@/lib/notification-preferences";
import type { PortfolioData } from "@/lib/portfolio";
import type { MaintenanceTicket } from "@/lib/maintenance";
import type { InvitationListItem } from "@/lib/invitations";
import type { NotificationDTO } from "@/lib/notifications";
import type { OwnerDocumentsData } from "@/lib/documents";
import type { VendorDTO } from "@/lib/vendors";
import type { FeatureCapabilitiesDTO } from "@/lib/feature-capabilities";
import type {
  AccountDeleteRequestDTO,
  AccountRenameRequestDTO,
  OwnershipAccountDTO,
  OwnershipMemberDTO
} from "@/lib/ownership";
import type { ExpenseDashboardData } from "@/lib/expenses";
import type { AutomationRuleDTO, AutomationTemplateDTO } from "@/lib/automations";
import type { InboxThreadDTO } from "@/lib/inbox";
import type { RentalListingDTO } from "@/lib/leasing";
import type { ApplicationDTO } from "@/lib/applications";
import type { UserGamificationData } from "@/lib/gamification";
import type { AnalyticsDashboardData } from "@/lib/analytics";
import type { AuditLogEntry } from "@/lib/audit";
import type { RentIncreaseEntry } from "@/lib/rent-increases";
import type { DistributionHistoryEntry, FinancialActivityEvent } from "@/lib/distributions";
import type { DistributionChangeRequestDTO } from "@/lib/distribution-approvals";
import type { WithdrawalRequestDTO } from "@/lib/withdrawals";
import type {
  ManagerAssignmentOption,
  ManagerPaymentConfigDTO,
  ManagerPaymentDTO
} from "@/lib/manager-payments";
import type { ActionState } from "@/app/actions";
import type { ManagerWorkflowMode, OwnerWorkflowMode } from "./dashboard-config";

export type FormAction = (formData: FormData) => Promise<void>;
export type StatefulAction = (prev: ActionState, formData: FormData) => Promise<ActionState>;

export interface DashboardProps {
  data: DashboardData;
  isEmpty?: boolean;
  activeAccountId?: string | null;
  currentUserId?: string;
  portfolio?: PortfolioData;
  tickets?: MaintenanceTicket[];
  invitations?: InvitationListItem[];
  notifications?: NotificationDTO[];
  notificationPreferenceSettings?: NotificationPreferenceSettings | null;
  inboxThreads?: InboxThreadDTO[];
  documents?: OwnerDocumentsData;
  automationTemplates?: AutomationTemplateDTO[];
  automationRules?: AutomationRuleDTO[];
  vendors?: VendorDTO[];
  expensesData?: ExpenseDashboardData;
  capabilities?: FeatureCapabilitiesDTO;
  ownershipAccounts?: OwnershipAccountDTO[];
  ownershipMembers?: OwnershipMemberDTO[];
  pendingAccountRenameRequests?: AccountRenameRequestDTO[];
  pendingAccountDeleteRequests?: AccountDeleteRequestDTO[];
  distributionHistory?: DistributionHistoryEntry[];
  pendingChangeRequests?: DistributionChangeRequestDTO[];
  pendingWithdrawals?: WithdrawalRequestDTO[];
  financialActivityFeed?: FinancialActivityEvent[];
  listings?: RentalListingDTO[];
  applications?: ApplicationDTO[];
  managerPaymentConfigs?: ManagerPaymentConfigDTO[];
  managerPayments?: ManagerPaymentDTO[];
  managerPaymentManagers?: ManagerAssignmentOption[];
  managerPaymentsWarning?: string | null;
  applicationCount?: number;
  approvedApplicationCount?: number;
  gamification?: UserGamificationData;
  analyticsData?: AnalyticsDashboardData;
  auditLogs?: AuditLogEntry[];
  rentIncreaseHistory?: RentIncreaseEntry[];
  generatedMessage?: string | null;
  initialSectionId?: string | null;
  initialPropertyId?: string | null;
  initialOwnerWorkflowMode?: OwnerWorkflowMode;
  initialManagerWorkflowMode?: ManagerWorkflowMode;
  userEmail: string;
  fullName?: string | null;
  nickname?: string | null;
  avatarUrl?: string | null;
  stripeConnected?: boolean;
  ownerConnectedMap?: Map<string, boolean>;
  onGenerateChargesHref?: string;
  onSignOut: FormAction;
  onCreateProperty: StatefulAction;
  onCreateUnit: StatefulAction;
  onCreateLease: StatefulAction;
  onRenameProperty?: StatefulAction;
  onUpdateProperty?: StatefulAction;
  onDeleteProperty?: StatefulAction;
  onUpdateUnitField?: StatefulAction;
  onUpdateUnit?: StatefulAction;
  onDeleteUnit?: StatefulAction;
  onUpdateLease?: StatefulAction;
  onUpdateRentAmount?: StatefulAction;
  onUpdateTenantDisplayInfo?: StatefulAction;
  onUpdateManagerInfo?: StatefulAction;
  onDeleteLease?: StatefulAction;
  onRenewLease?: StatefulAction;
  onTerminateLease?: StatefulAction;
  onPayCharge: FormAction;
  onDeletePendingCharge?: StatefulAction;
  onEditCharge?: StatefulAction;
  onCreateManualCharge?: StatefulAction;
  onWaiveCharge?: StatefulAction;
  onRecordManualPayment?: StatefulAction;
  onSendMessageToTenant?: StatefulAction;
  onUpdateTicketStatus?: StatefulAction;
  onAddTicketComment?: StatefulAction;
  onInviteTenant?: StatefulAction;
  onInviteManager?: StatefulAction;
  onInviteOwner?: StatefulAction;
  onResendInvite?: StatefulAction;
  onRevokeInvite?: StatefulAction;
  onMarkNotificationRead?: StatefulAction;
  onMarkAllNotificationsRead?: StatefulAction;
  onResumeNotificationEmails?: StatefulAction;
  onSendBatchPaymentReminder?: StatefulAction;
  onCreateInboxThread?: StatefulAction;
  onSendInboxMessage?: StatefulAction;
  onEnableAutomation?: StatefulAction;
  onDisableAutomation?: StatefulAction;
  onCreateRentalListing?: StatefulAction;
  onUpdateListingStatus?: StatefulAction;
  onCreateApplication?: StatefulAction;
  onReviewApplication?: StatefulAction;
  onAddApplicationNote?: StatefulAction;
  onRecordScreeningScore?: StatefulAction;
  onCreateDocumentTemplate?: StatefulAction;
  onDeleteDocumentTemplate?: StatefulAction;
  onCreateDocumentPacket?: StatefulAction;
  onSendDocumentPacket?: StatefulAction;
  onUploadPropertyFile?: StatefulAction;
  onDeletePropertyFile?: StatefulAction;
  onUpdateFileVisibility?: StatefulAction;
  onCreateVendor?: StatefulAction;
  onUpdateVendor?: StatefulAction;
  onAssignVendor?: StatefulAction;
  onUploadMaintenancePhoto?: StatefulAction;
  onDeleteMaintenancePhoto?: StatefulAction;
  onCreateExpense?: StatefulAction;
  onUpdateExpense?: StatefulAction;
  onDeleteExpense?: StatefulAction;
  onSetupManagerPaymentConfig?: StatefulAction;
  onRecordManagerPayment?: StatefulAction;
  onMarkManagerPaymentPaid?: StatefulAction;
  onCancelManagerPayment?: StatefulAction;
  onGenerateMonthlyManagerPayments?: StatefulAction;
  onCreateOwnershipAccount?: StatefulAction;
  onLinkPropertyToOwnershipAccount?: StatefulAction;
  onRenameOwnershipAccount?: StatefulAction;
  onRemoveOwnershipMember?: StatefulAction;
  onVoteOnAccountRename?: StatefulAction;
  onRequestDeleteLLC?: StatefulAction;
  onVoteOnDeleteLLC?: StatefulAction;
  onInitiateAccountStripeConnect?: StatefulAction;
  onUpdateDistributionConfig?: StatefulAction;
  onSubmitDistributionChangeRequest?: StatefulAction;
  onVoteOnDistributionChange?: StatefulAction;
  onInitiateMemberPayoutConnect?: StatefulAction;
  onSubmitWithdrawalRequest?: StatefulAction;
  onVoteOnWithdrawal?: StatefulAction;
  onInitiatePlaidLink?: StatefulAction;
  onCompletePlaidLink?: StatefulAction;
  onRefreshPlaidBalance?: StatefulAction;
  onDisconnectPlaid?: StatefulAction;
  onExecuteApprovedWithdrawal?: StatefulAction;
  onUpdateManagementFee?: StatefulAction;
}
