import type { DashboardData } from "@/lib/dashboard";
import type { PortfolioData } from "@/lib/portfolio";
import type { MaintenanceTicket } from "@/lib/maintenance";
import type { InvitationListItem } from "@/lib/invitations";
import type { NotificationDTO } from "@/lib/notifications";
import type { OwnerDocumentsData } from "@/lib/documents";
import type { VendorDTO } from "@/lib/vendors";
import type { FeatureCapabilitiesDTO } from "@/lib/feature-capabilities";
import type { OwnershipAccountDTO, OwnershipMemberDTO } from "@/lib/ownership";
import type { ExpenseDashboardData } from "@/lib/expenses";
import type { AutomationRuleDTO, AutomationTemplateDTO } from "@/lib/automations";
import type { InboxThreadDTO } from "@/lib/inbox";
import type { RentalListingDTO } from "@/lib/leasing";
import type { ApplicationDTO } from "@/lib/applications";
import type { UserGamificationData } from "@/lib/gamification";
import type { AnalyticsDashboardData } from "@/lib/analytics";
import type { AuditLogEntry } from "@/lib/audit";
import type { RentIncreaseEntry } from "@/lib/rent-increases";
import type { DistributionHistoryEntry } from "@/lib/distributions";
import type { ActionState } from "@/app/actions";
import type { ManagerWorkflowMode, OwnerWorkflowMode } from "./dashboard-config";

export type FormAction = (formData: FormData) => Promise<void>;
export type StatefulAction = (prev: ActionState, formData: FormData) => Promise<ActionState>;

export interface DashboardProps {
  data: DashboardData;
  isEmpty?: boolean;
  activeAccountId?: string | null;
  portfolio?: PortfolioData;
  tickets?: MaintenanceTicket[];
  invitations?: InvitationListItem[];
  notifications?: NotificationDTO[];
  inboxThreads?: InboxThreadDTO[];
  documents?: OwnerDocumentsData;
  automationTemplates?: AutomationTemplateDTO[];
  automationRules?: AutomationRuleDTO[];
  vendors?: VendorDTO[];
  expensesData?: ExpenseDashboardData;
  capabilities?: FeatureCapabilitiesDTO;
  ownershipAccounts?: OwnershipAccountDTO[];
  ownershipMembers?: OwnershipMemberDTO[];
  distributionHistory?: DistributionHistoryEntry[];
  listings?: RentalListingDTO[];
  applications?: ApplicationDTO[];
  applicationCount?: number;
  approvedApplicationCount?: number;
  gamification?: UserGamificationData;
  analyticsData?: AnalyticsDashboardData;
  auditLogs?: AuditLogEntry[];
  rentIncreaseHistory?: RentIncreaseEntry[];
  generatedMessage?: string | null;
  initialSectionId?: string | null;
  initialOwnerWorkflowMode?: OwnerWorkflowMode;
  initialManagerWorkflowMode?: ManagerWorkflowMode;
  userEmail: string;
  fullName?: string | null;
  nickname?: string | null;
  avatarUrl?: string | null;
  stripeConnected?: boolean;
  ownerConnectedMap?: Map<string, boolean>;
  onGenerateChargesHref?: string;
  onSignOut: FormAction;
  onCreateProperty: StatefulAction;
  onCreateUnit: StatefulAction;
  onCreateLease: StatefulAction;
  onUpdateProperty?: StatefulAction;
  onDeleteProperty?: StatefulAction;
  onUpdateUnit?: StatefulAction;
  onDeleteUnit?: StatefulAction;
  onUpdateLease?: StatefulAction;
  onDeleteLease?: StatefulAction;
  onRenewLease?: StatefulAction;
  onTerminateLease?: StatefulAction;
  onPayCharge: FormAction;
  onRecordManualPayment?: StatefulAction;
  onUpdateTicketStatus?: StatefulAction;
  onAddTicketComment?: StatefulAction;
  onInviteTenant?: StatefulAction;
  onInviteManager?: StatefulAction;
  onInviteOwner?: StatefulAction;
  onResendInvite?: StatefulAction;
  onMarkNotificationRead?: StatefulAction;
  onMarkAllNotificationsRead?: StatefulAction;
  onCreateInboxThread?: StatefulAction;
  onSendInboxMessage?: StatefulAction;
  onEnableAutomation?: StatefulAction;
  onDisableAutomation?: StatefulAction;
  onCreateRentalListing?: StatefulAction;
  onUpdateListingStatus?: StatefulAction;
  onCreateApplication?: StatefulAction;
  onReviewApplication?: StatefulAction;
  onAddApplicationNote?: StatefulAction;
  onRecordScreeningScore?: StatefulAction;
  onCreateDocumentTemplate?: StatefulAction;
  onDeleteDocumentTemplate?: StatefulAction;
  onCreateDocumentPacket?: StatefulAction;
  onSendDocumentPacket?: StatefulAction;
  onUploadPropertyFile?: StatefulAction;
  onDeletePropertyFile?: StatefulAction;
  onUpdateFileVisibility?: StatefulAction;
  onCreateVendor?: StatefulAction;
  onUpdateVendor?: StatefulAction;
  onAssignVendor?: StatefulAction;
  onUploadMaintenancePhoto?: StatefulAction;
  onCreateExpense?: StatefulAction;
  onUpdateExpense?: StatefulAction;
  onDeleteExpense?: StatefulAction;
  onCreateOwnershipAccount?: StatefulAction;
  onLinkPropertyToOwnershipAccount?: StatefulAction;
  onInitiateAccountStripeConnect?: StatefulAction;
  onUpdateDistributionConfig?: StatefulAction;
  onInitiateMemberPayoutConnect?: StatefulAction;
  onUpdateManagementFee?: StatefulAction;
}
